### ISSUE TITLE
some problem about infer.py

### ISSUE THREAD

**Issue by stefenmax** [lzhengchun/TomoGAN#1]
Thanks for you nice work,I trained your modle with my dataset successfully in your h5 format,but when I use you infer function to test,some error rasied.

ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (30, 512, 512)

Could you tell me how you fix it?

Thanks

**Comment by lzhengchun** [comment]
Oh, sorry. infer.py is not well tested. the input must be 4 dimension, i.e., (N, H, W, C), as your input is gray scale, we need add a placeholder dimension for the Channel. I commit a version to fix it. basically, you need to make your input to be (30, 512, 512, 1)

**Comment by lzhengchun** [comment]
I believe the issue has been fixed, feel free to reopen if problem persistent

**Comment by stefenmax** [comment]
Thanks for your reply,it did works,but when I want adjust some parameters in your code,I find other problems.

**First**,I thought the **depth** is one of your important parameters ,but when I tried to adjust it,some error rasied.

ValueError: Error when checking input: expected input_1 to have shape (None, None, 4) but got array with shape (512, 512, 1)

Does it means I need to do some data preprocess？

**Second**,I have two Nvidia 1080TI to use,how could I use it in the same time,I juse tried -gpus 0,1 But it didn't work.

Could you tell me how to fix it?

Thanks a lot!

**Comment by lzhengchun** [comment]
to your 1st Q, I fixed it, it seems that the tf1 version and tf2 version is not sync'ed, i probably should not separate them

to your 2nd Q, this implementation doesnot support multiple GPU.

**Comment by stefenmax** [comment]
Thanks,it helps me a lot.

**Comment by stefenmax** [comment]
Emm,when I trained a network with depth 3 and want to test it,I found that the infer.py may not concern about the depth,some error rasied.

ValueError: Error when checking input: expected input_1 to have shape (None, None, 3) but got array with shape

Sorry for bothering you timely.

**Comment by lzhengchun** [comment]
yes, the infer.py doesnot support. actually infer.py was not planned to be released, I will update it when I get a chance. or you can try it and ask for merge.

**Comment by stefenmax** [comment]
Yeah,I found the old version about infer.py and fix it.

You can uodate it when you have time.

Thanks anyway.
